[package]
name = "rse-server-plugin"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
rse-cpp.workspace = true
rse-game.workspace = true
rse-game-interfaces.workspace = true
rse-interface.workspace = true
