[workspace]
resolver = "3"
members = [
	"rse-cpp",
	"rse-interface",
	"rse-game",
	"rse-game-interfaces",
	"rse-tier0",
	"rse-server-plugin",
	"test-server-plugin",
]

[workspace.dependencies]
cppdvt = { git = "https://github.com/b0mbie/cppdvt.git" }

rse-cpp = { path = "./rse-cpp" }
rse-interface = { path = "./rse-interface" }
rse-game = { path = "./rse-game" }
rse-game-interfaces = { path = "./rse-game-interfaces" }
rse-server-plugin = { path = "./rse-server-plugin" }
rse-tier0 = { path = "./rse-tier0" }
rse-tier0-log = { path = "./rse-tier0-log" }
