[package]
name = "console"
version = "0.1.0"
edition = "2024"
publish = false

[features]
link-srv = ["rse-std/link-srv"]

[lib]
name = "console"
crate-type = ["cdylib"]

[dependencies]
rse-std.workspace = true
