[package]
name = "test-std-plugin"
version = "0.1.0"
edition = "2024"
publish = false

[features]
link-srv = ["rse-std/link-srv"]

[lib]
name = "test_std"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
rse-std.workspace = true
