[package]
name = "test-server-plugin"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
printf.workspace = true
rse-server-plugin.workspace = true
rse-tier0.workspace = true
rse-tier0-print.workspace = true
