[package]
name = "rse-tier0"
version = "0.1.0"
edition = "2024"

[features]
default = ["link-dll", "link-srv"]
link-dll = []
link-srv = []

[dependencies]
rse-cpp.workspace = true
rse-game.workspace = true
