[package]
name = "rse-plugin"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
rse-convar.workspace = true
rse-cpp.workspace = true
rse-shared.workspace = true
rse-game-interfaces.workspace = true
rse-interface.workspace = true
